# Generated by Django 3.2.6 on 2021-08-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(default='', max_length=300)),
                ('market_name', models.CharField(default='', max_length=300)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
    ]
