# Generated by Django 3.2.6 on 2021-08-31 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agprice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='price/', verbose_name='ภาพประกอบ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='วันที่ประกาศ'),
        ),
        migrations.AlterField(
            model_name='price',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='รหัส'),
        ),
        migrations.AlterField(
            model_name='price',
            name='market_name',
            field=models.CharField(default='', max_length=300, verbose_name='ตลาด'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='ราคา'),
        ),
        migrations.AlterField(
            model_name='price',
            name='product_name',
            field=models.CharField(default='', max_length=300, verbose_name='สินค้า'),
        ),
    ]
